---
https:
  listenAddress: '0.0.0.0'
  listenPort: 44381
  publicCertFile: 'sharpblog-dev-public.cer'
  privateCertFile: 'sharpblog-dev-private.pfx'

blog:
  title: 'SharpBlog'
  staticUrl: 'https://localhost:44381'
  apiUrl: 'https://localhost:44380'
  webUrl: 'https://localhost:44381'
  adminUrl: 'https://localhost:44382'
  githubUrl: 'https://github.com/cnsimo'
  telegramUrl: 'https://t.me/reinj3ct'